name: Build
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "yarn"
      - run: yarn
      - run: yarn build